// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

/*
Package entity is a generated protocol buffer package.

It is generated from these files:
	entity.proto

It has these top-level messages:
	ProtoRecord
	ProtoTick
*/
package entity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoRecord struct {
	Date   int64   `protobuf:"zigzag64,1,opt,name=date" json:"date,omitempty"`
	Open   float64 `protobuf:"fixed64,2,opt,name=open" json:"open,omitempty"`
	Close  float64 `protobuf:"fixed64,3,opt,name=close" json:"close,omitempty"`
	High   float64 `protobuf:"fixed64,4,opt,name=high" json:"high,omitempty"`
	Low    float64 `protobuf:"fixed64,5,opt,name=low" json:"low,omitempty"`
	Volume float64 `protobuf:"fixed64,6,opt,name=volume" json:"volume,omitempty"`
	Amount float64 `protobuf:"fixed64,7,opt,name=amount" json:"amount,omitempty"`
}

func (m *ProtoRecord) Reset()                    { *m = ProtoRecord{} }
func (m *ProtoRecord) String() string            { return proto.CompactTextString(m) }
func (*ProtoRecord) ProtoMessage()               {}
func (*ProtoRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoRecord) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ProtoRecord) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *ProtoRecord) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *ProtoRecord) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *ProtoRecord) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *ProtoRecord) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *ProtoRecord) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ProtoTick struct {
	Code        string    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Timestamp   int64     `protobuf:"zigzag64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	HighLimited float64   `protobuf:"fixed64,3,opt,name=highLimited" json:"highLimited,omitempty"`
	LowLimited  float64   `protobuf:"fixed64,4,opt,name=lowLimited" json:"lowLimited,omitempty"`
	Price       float64   `protobuf:"fixed64,5,opt,name=price" json:"price,omitempty"`
	Position    float64   `protobuf:"fixed64,6,opt,name=position" json:"position,omitempty"`
	Settle      float64   `protobuf:"fixed64,7,opt,name=settle" json:"settle,omitempty"`
	Open        float64   `protobuf:"fixed64,8,opt,name=open" json:"open,omitempty"`
	Close       float64   `protobuf:"fixed64,9,opt,name=close" json:"close,omitempty"`
	High        float64   `protobuf:"fixed64,10,opt,name=high" json:"high,omitempty"`
	Low         float64   `protobuf:"fixed64,11,opt,name=low" json:"low,omitempty"`
	Volume      float64   `protobuf:"fixed64,12,opt,name=volume" json:"volume,omitempty"`
	TotalVolume float64   `protobuf:"fixed64,13,opt,name=totalVolume" json:"totalVolume,omitempty"`
	Amount      float64   `protobuf:"fixed64,14,opt,name=amount" json:"amount,omitempty"`
	TotalAmount float64   `protobuf:"fixed64,15,opt,name=totalAmount" json:"totalAmount,omitempty"`
	PreSettle   float64   `protobuf:"fixed64,16,opt,name=preSettle" json:"preSettle,omitempty"`
	PrePosition float64   `protobuf:"fixed64,17,opt,name=prePosition" json:"prePosition,omitempty"`
	PreClose    float64   `protobuf:"fixed64,18,opt,name=preClose" json:"preClose,omitempty"`
	AskPrices   []float64 `protobuf:"fixed64,19,rep,packed,name=askPrices" json:"askPrices,omitempty"`
	AskVolumes  []float64 `protobuf:"fixed64,20,rep,packed,name=askVolumes" json:"askVolumes,omitempty"`
	BidPrices   []float64 `protobuf:"fixed64,21,rep,packed,name=bidPrices" json:"bidPrices,omitempty"`
	BidVolumes  []float64 `protobuf:"fixed64,22,rep,packed,name=bidVolumes" json:"bidVolumes,omitempty"`
	Side        int32     `protobuf:"zigzag32,23,opt,name=side" json:"side,omitempty"`
}

func (m *ProtoTick) Reset()                    { *m = ProtoTick{} }
func (m *ProtoTick) String() string            { return proto.CompactTextString(m) }
func (*ProtoTick) ProtoMessage()               {}
func (*ProtoTick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoTick) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ProtoTick) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProtoTick) GetHighLimited() float64 {
	if m != nil {
		return m.HighLimited
	}
	return 0
}

func (m *ProtoTick) GetLowLimited() float64 {
	if m != nil {
		return m.LowLimited
	}
	return 0
}

func (m *ProtoTick) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProtoTick) GetPosition() float64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *ProtoTick) GetSettle() float64 {
	if m != nil {
		return m.Settle
	}
	return 0
}

func (m *ProtoTick) GetOpen() float64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *ProtoTick) GetClose() float64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *ProtoTick) GetHigh() float64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *ProtoTick) GetLow() float64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *ProtoTick) GetVolume() float64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *ProtoTick) GetTotalVolume() float64 {
	if m != nil {
		return m.TotalVolume
	}
	return 0
}

func (m *ProtoTick) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ProtoTick) GetTotalAmount() float64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *ProtoTick) GetPreSettle() float64 {
	if m != nil {
		return m.PreSettle
	}
	return 0
}

func (m *ProtoTick) GetPrePosition() float64 {
	if m != nil {
		return m.PrePosition
	}
	return 0
}

func (m *ProtoTick) GetPreClose() float64 {
	if m != nil {
		return m.PreClose
	}
	return 0
}

func (m *ProtoTick) GetAskPrices() []float64 {
	if m != nil {
		return m.AskPrices
	}
	return nil
}

func (m *ProtoTick) GetAskVolumes() []float64 {
	if m != nil {
		return m.AskVolumes
	}
	return nil
}

func (m *ProtoTick) GetBidPrices() []float64 {
	if m != nil {
		return m.BidPrices
	}
	return nil
}

func (m *ProtoTick) GetBidVolumes() []float64 {
	if m != nil {
		return m.BidVolumes
	}
	return nil
}

func (m *ProtoTick) GetSide() int32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoRecord)(nil), "entity.ProtoRecord")
	proto.RegisterType((*ProtoTick)(nil), "entity.ProtoTick")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x4e, 0xf3, 0x30,
	0x10, 0x84, 0x95, 0xbf, 0x6d, 0xfe, 0xc6, 0x29, 0xd0, 0x9a, 0x52, 0x2c, 0x84, 0x50, 0xd4, 0x53,
	0x4f, 0x5c, 0x78, 0x02, 0xc4, 0x95, 0x43, 0x15, 0x10, 0xf7, 0x34, 0x59, 0x51, 0xab, 0x49, 0x1c,
	0xc5, 0x2e, 0x15, 0x8f, 0xc3, 0x63, 0x72, 0x43, 0xeb, 0x75, 0x52, 0x23, 0x7a, 0xdb, 0xf9, 0xec,
	0x71, 0x77, 0xa6, 0x0a, 0x9b, 0x40, 0x6d, 0xa4, 0xf9, 0xbc, 0x6f, 0x5a, 0x65, 0x14, 0x0f, 0x49,
	0x2d, 0xbf, 0x02, 0x16, 0xaf, 0x91, 0xa4, 0x90, 0xab, 0xb6, 0xe0, 0x9c, 0x0d, 0x8b, 0xcc, 0x80,
	0x08, 0x92, 0x60, 0xc5, 0x53, 0x3b, 0x23, 0x53, 0x0d, 0xd4, 0xe2, 0x5f, 0x12, 0xac, 0x82, 0xd4,
	0xce, 0x7c, 0xce, 0x46, 0x79, 0xa9, 0x34, 0x88, 0x81, 0x85, 0x24, 0xf0, 0xe6, 0x56, 0xbe, 0x6f,
	0xc5, 0x90, 0x6e, 0xe2, 0xcc, 0xa7, 0x6c, 0x50, 0xaa, 0x83, 0x18, 0x59, 0x84, 0x23, 0x5f, 0xb0,
	0xf0, 0x43, 0x95, 0xfb, 0x0a, 0x44, 0x68, 0xa1, 0x53, 0xc8, 0xb3, 0x4a, 0xed, 0x6b, 0x23, 0xfe,
	0x13, 0x27, 0xb5, 0xfc, 0x1e, 0xb2, 0xc8, 0xee, 0xf8, 0x2a, 0xf3, 0x1d, 0xfe, 0x46, 0xae, 0x0a,
	0xda, 0x30, 0x4a, 0xed, 0xcc, 0x6f, 0x59, 0x64, 0x64, 0x05, 0xda, 0x64, 0x55, 0x63, 0xd7, 0xe4,
	0xe9, 0x11, 0xf0, 0x84, 0xc5, 0xb8, 0xc9, 0xb3, 0xac, 0xa4, 0x81, 0xc2, 0x6d, 0xec, 0x23, 0x7e,
	0xc7, 0x58, 0xa9, 0x0e, 0xdd, 0x05, 0xda, 0xde, 0x23, 0x98, 0xb6, 0x69, 0x65, 0x0e, 0x2e, 0x05,
	0x09, 0x7e, 0xc3, 0xc6, 0x8d, 0xd2, 0xd2, 0x48, 0x55, 0xbb, 0x24, 0xbd, 0xc6, 0x2c, 0x1a, 0x8c,
	0x29, 0xa1, 0xcb, 0x42, 0xaa, 0xef, 0x72, 0x7c, 0xaa, 0xcb, 0xe8, 0x54, 0x97, 0xec, 0x6f, 0x97,
	0xf1, 0xa9, 0x2e, 0x27, 0xbf, 0xba, 0x4c, 0x58, 0x6c, 0x94, 0xc9, 0xca, 0x37, 0x3a, 0x3c, 0xa3,
	0xcc, 0x1e, 0xf2, 0xda, 0x3e, 0xf7, 0xdb, 0xee, 0x9d, 0x8f, 0x74, 0x78, 0xe1, 0x39, 0x09, 0x61,
	0xdb, 0x4d, 0x0b, 0x2f, 0x14, 0x6f, 0x6a, 0xcf, 0x8f, 0x00, 0xfd, 0x4d, 0x0b, 0xeb, 0xae, 0x98,
	0x19, 0xf9, 0x3d, 0x64, 0x7b, 0x6b, 0xe1, 0xc9, 0x46, 0xe6, 0xae, 0x37, 0xa7, 0xf1, 0xed, 0x4c,
	0xef, 0xd6, 0xd8, 0xaf, 0x16, 0x97, 0xc9, 0x00, 0xdf, 0xee, 0x01, 0xfe, 0x4f, 0x99, 0xde, 0x51,
	0x00, 0x2d, 0xe6, 0xf6, 0xd8, 0x23, 0xe8, 0xde, 0xc8, 0xc2, 0xb9, 0xaf, 0xc8, 0xdd, 0x03, 0x74,
	0x6f, 0x64, 0xd1, 0xb9, 0x17, 0xe4, 0x3e, 0x12, 0x6c, 0x5c, 0xcb, 0x02, 0xc4, 0x75, 0x12, 0xac,
	0x66, 0xa9, 0x9d, 0x37, 0xa1, 0xfd, 0x5c, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x58,
	0x1d, 0x45, 0x3e, 0x03, 0x00, 0x00,
}
